-- Atualizacao de estrutura para funcionalidades de automatizacoes financeiras e dashboard
-- Execute em um banco SQL Server antes de publicar as alteracoes de codigo

IF OBJECT_ID('TB_DESPESAS_FIXAS', 'U') IS NULL
BEGIN
    CREATE TABLE TB_DESPESAS_FIXAS (
        ID_DESPESA_FIXA INT IDENTITY(1,1) PRIMARY KEY,
        DESCRICAO NVARCHAR(200) NOT NULL,
        VALOR_PADRAO NUMERIC(19,2) NOT NULL,
        DIA_VENCIMENTO TINYINT NULL,
        ID_FORNECEDOR INT NULL,
        ATIVA BIT NOT NULL DEFAULT 1,
        ID_USUARIO INT NULL,
        DT_CRIACAO DATETIME NOT NULL DEFAULT GETDATE()
    );
END

IF OBJECT_ID('TB_DESPESAS_FIXAS_LANCAMENTOS', 'U') IS NULL
BEGIN
    CREATE TABLE TB_DESPESAS_FIXAS_LANCAMENTOS (
        ID_LANCAMENTO INT IDENTITY(1,1) PRIMARY KEY,
        ID_DESPESA_FIXA INT NOT NULL,
        COMPETENCIA INT NOT NULL,
        DT_VENCIMENTO DATE NOT NULL,
        VL_PREVISTO NUMERIC(19,2) NOT NULL,
        VL_CONFIRMADO NUMERIC(19,2) NULL,
        STATUS VARCHAR(20) NOT NULL DEFAULT 'AGUARDANDO',
        DT_CONFIRMACAO DATETIME NULL,
        ID_USUARIO_CONFIRMACAO INT NULL,
        ID_USUARIO_CRIACAO INT NULL,
        ID_PAGAMENTO INT NULL,
        OBSERVACAO NVARCHAR(200) NULL
    );

    CREATE INDEX IX_DESPESAS_FIXAS_LANC_COMPETENCIA ON TB_DESPESAS_FIXAS_LANCAMENTOS (COMPETENCIA);
    CREATE INDEX IX_DESPESAS_FIXAS_LANC_STATUS ON TB_DESPESAS_FIXAS_LANCAMENTOS (STATUS);
END

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_DESPESA_FIXA_LANC_DESPESA'
)
BEGIN
    ALTER TABLE TB_DESPESAS_FIXAS_LANCAMENTOS WITH NOCHECK
    ADD CONSTRAINT FK_DESPESA_FIXA_LANC_DESPESA FOREIGN KEY (ID_DESPESA_FIXA) REFERENCES TB_DESPESAS_FIXAS(ID_DESPESA_FIXA);
END

IF OBJECT_ID('TB_PARCELAMENTOS', 'U') IS NULL
BEGIN
    CREATE TABLE TB_PARCELAMENTOS (
        DESCRICAO NVARCHAR(200) NOT NULL,
        VALOR_TOTAL NUMERIC(19,2) NOT NULL,
        JUROS_PERCENTUAL NUMERIC(9,4) NULL,
        JUROS_TOTAL NUMERIC(19,2) NULL,
        DT_PRIMEIRA_PARCELA DATE NOT NULL,
        ID_FORNECEDOR INT NULL,
        ID_USUARIO INT NULL,
        DT_CADASTRO DATETIME NOT NULL DEFAULT GETDATE()
    );

    CREATE INDEX IX_PARCELAMENTOS_DT_PRIMEIRA ON TB_PARCELAMENTOS (DT_PRIMEIRA_PARCELA);
END





IF NOT EXISTS (
)
BEGIN
END

IF COL_LENGTH('TB_SERVICOS_CLIENTE', 'FL_ATIVO') IS NULL
BEGIN
    ALTER TABLE TB_SERVICOS_CLIENTE ADD FL_ATIVO BIT NOT NULL CONSTRAINT DF_SERVICO_CLIENTE_FL_ATIVO DEFAULT (1);
END

IF COL_LENGTH('TB_SERVICOS_CLIENTE', 'DT_FIM') IS NULL
    ALTER TABLE TB_SERVICOS_CLIENTE ADD DT_FIM DATE NULL;

IF COL_LENGTH('TB_SERVICOS_CLIENTE', 'DIA_VENCIMENTO') IS NULL
    ALTER TABLE TB_SERVICOS_CLIENTE ADD DIA_VENCIMENTO TINYINT NULL;

IF COL_LENGTH('TB_SERVICOS_CLIENTE', 'ULTIMA_COMPETENCIA_GERADA') IS NULL
    ALTER TABLE TB_SERVICOS_CLIENTE ADD ULTIMA_COMPETENCIA_GERADA INT NULL;

IF COL_LENGTH('TB_CARGOS_FUNCIONARIOS', 'VL_PROV_DECIMO_TERCEIRO') IS NULL
    ALTER TABLE TB_CARGOS_FUNCIONARIOS ADD VL_PROV_DECIMO_TERCEIRO NUMERIC(19,2) NULL;

IF COL_LENGTH('TB_CARGOS_FUNCIONARIOS', 'VL_PROV_FERIAS') IS NULL
    ALTER TABLE TB_CARGOS_FUNCIONARIOS ADD VL_PROV_FERIAS NUMERIC(19,2) NULL;

IF COL_LENGTH('TB_CARGOS_FUNCIONARIOS', 'VL_CUSTO_TOTAL') IS NULL
    ALTER TABLE TB_CARGOS_FUNCIONARIOS ADD VL_CUSTO_TOTAL NUMERIC(19,2) NULL;

IF COL_LENGTH('TB_CARGOS_FUNCIONARIOS', 'FL_LANCAR_AUTOMATICO') IS NULL
BEGIN
    ALTER TABLE TB_CARGOS_FUNCIONARIOS ADD FL_LANCAR_AUTOMATICO BIT NOT NULL CONSTRAINT DF_CARGOS_FUNC_FL_AUTO DEFAULT (0);
END

UPDATE TB_CARGOS_FUNCIONARIOS
SET FL_LANCAR_AUTOMATICO = COALESCE(FL_LANCAR_AUTOMATICO, 0);

UPDATE TB_CARGOS_FUNCIONARIOS
SET VL_PROV_DECIMO_TERCEIRO = COALESCE(VL_PROV_DECIMO_TERCEIRO, 0),
    VL_PROV_FERIAS = COALESCE(VL_PROV_FERIAS, 0),
    VL_CUSTO_TOTAL = COALESCE(VL_CUSTO_TOTAL, VL_SALARIO)
WHERE VL_CUSTO_TOTAL IS NULL;

-- Garante que servi?os existentes permane?am ativos ap?s a cria??o da coluna
UPDATE TB_SERVICOS_CLIENTE
SET FL_ATIVO = 1
WHERE FL_ATIVO IS NULL;

